services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/Europe/Paris
      - WEBUI_PORT=8080
    volumes:
      - ./volumes/qbittorrent-config:/config
      - /media/pi/NAS/tmp:/downloads
    ports:
      - 8080:8080
      - 30263:6881
      - 30263:6881/udp
    restart: no
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./volumes/jackett/config:/config
    ports:
      - 9117:9117
    restart: no
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Paris
    ports:
      - "${PORT:-8191}:8191"
    restart: no
  joal:
    image: anthonyraymond/joal:latest
    container_name: joal
    ports:
      - 9000:9000
    volumes:
      - ./volumes/joal/data:/data
    command:
      - --joal-conf=/data
      - --spring.main.web-environment=true
      - --server.port=9000
      - --joal.ui.path.prefix=${JOAL_PREFIX}
      - --joal.ui.secret-token=${JOAL_SECRET}