#https://beets.readthedocs.io/en/stable/reference/config.html
directory: /media/pi/NAS/music/library
library: /media/pi/NAS/music/beets-library.db
clutter: [ "Thumbs.DB", ".DS_Store", ".jpg", ".png", ".txt", ".nfo", ".lyrics", ".directory", ".m3u"]
ui:
  color: yes
import:
  move: yes

plugins: fetchart lastgenre replaygain badfiles convert discogs lyrics spotify duplicates missing fish ihate fromfilename mbsync bandcamp #mpdupdate
replaygain:
  backend: ffmpeg
convert:
  dest: /media/pi/NAS/music/exports
badfiles:
  check_on_import: yes
  commands:
    ogg: oggz validate
discogs:
  user_token: WaNvKyEbEtsRGLqQGrSMWjtrONOondGSsTBEPMRO
  source_weight: 0.7
spotify:
  source_weight: 0.9
#mpd:
#    host: localhost
#    port: 6604
ihate:
    warn:
      - format:mp3 bitrate:..192000
fetchart:
  minwidth: 360
lyrics:
  auto: yes
