version: "3"

services:
  pihole:
    container_name: adguard
    image: adguard/adguardhome:latest
    ports:
      - "10053:53/tcp"
      - "10053:53/udp"
      - "10067:67/udp"
      - "10068:68/udp"
      - "10068:68/tcp"
      - "10080:80/tcp"
      - "10443:443/tcp"
      - "10853:853/tcp"
      - "13000:3000/tcp"
    volumes:
       - './volumes/work:/opt/adguardhome/work'
       - './volumes/conf:/opt/adguardhome/conf'
    restart: unless-stopped