services:
  mympd:
    image: ghcr.io/jcorporation/mympd/mympd
    container_name: mympd
    user: 1000:1000
    network_mode: "host"
    environment:
      - UMASK_SET=022
      - MYMPD_SSL=false
      - MPD_HOST=/run/mpd/socket
      - MYMPD_HTTP_PORT=7700
      # - MYMPD_URI=http://rpi4.lemmie:7700
    volumes:
      - ~/.mpd/socket:/run/mpd/socket
      - ~/.mpd/playlists:/playlists
      - ./volumes/mympd/work:/var/lib/mympd
      - ./volumes/mympd/cache:/var/cache/mympd
      - /media/pi/NAS/music/library:/music